"""
report.py
---------
Emits the browsable record of a solved test: `run.json` plus the HTML views
built from it.

Data flows one way. The solver produces `run.json` — the encoded truth about a
run — and every other view is derived from it, never hand-written:

    solver + validator  ->  run.json  ->  index.html   (this test)
                                      ->  ../index.html (all tests)
                                      ->  render_run.py (PNGs, offline)

Where the output lands, all under the plots directory::

    plots/tests/index.html              every run, one table -- the entry point
    plots/tests/<name>/run.json         the encoded record for one run
    plots/tests/<name>/index.html       that run's report
    plots/tests/<name>/png_from_json/   only when render_run.py is invoked

``<name>`` is the test's name with spaces replaced by underscores, matching the
folder ``run_tests.py`` already writes its other artifacts into.

Two properties make this work as a replacement for a folder of images:

* **Text, not pixels.** A grid is a wall bitstring plus two robot positions per
  frame, so a whole run is kilobytes where the PNGs were megabytes, it diffs in
  git, and `repomix`/`graphify` can actually read it.
* **Self-contained HTML.** Browsers refuse `fetch()` over `file://`, so the JSON
  is inlined into the page rather than loaded beside it. The report opens by
  double-click, with no server.

The markup itself lives in ``src/templates/*.html.j2`` and is rendered with
Jinja2 — see :data:`TEMPLATE_DIR`.

Nothing here is written by hand and nothing is tracked: every artifact is
regenerated by the next run and overwritten in place.
"""

from __future__ import annotations

import glob
import json
import os
from datetime import datetime, timezone

from jinja2 import Environment, FileSystemLoader, select_autoescape

#: Bumped when the shape of run.json changes incompatibly. Readers (the HTML
#: template, render_run.py, the global index) check it before trusting a file,
#: so a stale run.json left over from an older version fails loudly instead of
#: rendering a subtly wrong picture.
SCHEMA_VERSION = 1

RUN_FILENAME = "run.json"
REPORT_FILENAME = "index.html"

#: The markup lives in real ``.html.j2`` files rather than Python strings, so an
#: editor highlights and lints the HTML, CSS and JS, and Jinja's autoescaping
#: covers every interpolation instead of each call site remembering to escape.
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")

_ENV = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(default_for_string=True, default=True),
    trim_blocks=True,
    lstrip_blocks=True,
)


# ── encoding ────────────────────────────────────────────────────────────


def encode_grid(grid) -> dict:
    """A grid as ``{rows, cols, walls}`` with walls row-major, '1' = obstacle.

    A bitstring rather than a nested list: it is a fifth of the JSON bytes and
    indexes directly as ``walls[r * cols + c]`` in both Python and JavaScript,
    so the renderer needs no unpacking step.
    """
    return {
        "rows": grid.rows,
        "cols": grid.cols,
        "walls": "".join(
            "1" if grid.tiles[r][c] != 0 else "0"
            for r in range(grid.rows)
            for c in range(grid.cols)
        ),
    }


def _frames(snapshots, titles) -> list[dict]:
    """One entry per validator step: both robot positions and what moved.

    Kept at full step resolution rather than collapsed to turns, because the
    report animates individual moves; `_turns` covers the coarser view.
    """
    out = []
    for i, ((a, b), title) in enumerate(zip(snapshots, titles)):
        moved = None
        if i:
            prev_a, prev_b = snapshots[i - 1]
            if (a.row, a.col) != (prev_a.row, prev_a.col):
                moved = a.label
            elif (b.row, b.col) != (prev_b.row, prev_b.col):
                moved = b.label
        out.append(
            {
                "i": i,
                "title": title,
                "a": [a.row, a.col],
                "b": [b.row, b.col],
                "moved": moved,
            }
        )
    return out


def _moves(waypoints) -> str:
    """The turn's command letters, read off consecutive waypoint centers.

    Derived from geometry rather than parsed out of the compact path notation:
    the positions are already exact, so this cannot disagree with what the board
    actually shows. Rows grow downward, hence +y is ``D``.
    """
    letters = []
    for (x0, y0), (x1, y1) in zip(waypoints, waypoints[1:]):
        if x1 > x0:
            letters.append("R" * round(x1 - x0))
        elif x1 < x0:
            letters.append("L" * round(x0 - x1))
        elif y1 > y0:
            letters.append("D" * round(y1 - y0))
        elif y1 < y0:
            letters.append("U" * round(y0 - y1))
    return "".join(letters)


def _turns(grid, snapshots, titles) -> list[dict]:
    """The per-switch segments, as the transition strip and chart show them.

    Delegates to the visualizer's extractor instead of re-deriving the
    segmentation: two implementations of "where does a turn end" would drift,
    and this one already defines what the PNGs mean. It touches no matplotlib,
    so importing it stays cheap.

    ``waypoints`` are the moving robot's successive centers, in cell units. They
    are what lets the report trace the route actually taken; keeping only the
    endpoints would draw every turn as a straight line from start to finish,
    which is wrong the moment a turn goes round a corner.
    """
    from src.visualizer import _contact_along_turn, _extract_turns

    out = []
    for turn in _extract_turns(snapshots, titles):
        start, end = turn["moving_start"], turn["moving_end"]
        waypoints = turn["waypoints"]
        # Walls contacted at any point during this turn, not just at its end --
        # the same per-turn highlight the PNG panels shade orange.
        wall_hits, _faces = _contact_along_turn(grid, turn)
        out.append(
            {
                "layer": turn["layer"],
                "label": end.label,
                "from": [start.row, start.col],
                "to": [end.row, end.col],
                "stationary": [turn["stationary"].row, turn["stationary"].col],
                "stationary_label": turn["stationary"].label,
                "waypoints": [[round(x, 3), round(y, 3)] for x, y in waypoints],
                "moves": _moves(waypoints),
                "steps": max(0, len(waypoints) - 1),
                "hits": [[r, c, n] for (r, c), n in sorted(wall_hits.items())],
            }
        )
    return out


def palette() -> dict:
    """The board colours, taken from ``visualizer`` so page and PNG cannot drift.

    The report used to re-declare these in CSS, which meant every colour existed
    twice and the two renderers slowly disagreed. Reading the module's constants
    keeps one definition; the template emits them as CSS custom properties.

    Imported lazily to match ``_turns`` -- and because ``visualizer`` defers
    matplotlib, this costs nothing in a solver worker.
    """
    from src import visualizer as viz

    return {
        "wall": viz.COLOR_OBSTACLE,
        "free": viz.COLOR_FREE,
        "grid": viz.COLOR_GRID_LINE,
        "a": viz.COLOR_ROBOT_A,
        "b": viz.COLOR_ROBOT_B,
        "arrow_a": viz.COLOR_ARROW_A,
        "arrow_b": viz.COLOR_ARROW_B,
        "hot": viz.COLOR_BLOCKER_WALL,
        "label": viz.COLOR_LABEL,
    }


def _heat(grid, snapshots) -> dict:
    """Wall-contact counts across the whole solve — the blocker heatmap's data.

    ``{max, cells: [[row, col, hits]], faces: [[row, col, side, hits]]}``, where
    ``side`` is the N/S/E/W face of the wall that met a robot. Only touched walls
    are listed: a heatmap is sparse, so sending the whole grid would be mostly
    zeros. This separates load-bearing walls from scenery, and is the input every
    simplification recipe thins.

    Imported lazily because ``simplify`` imports this module at module level;
    deferring to call time keeps that from being a cycle.
    """
    from src.simplify import _aggregate_wall_counts

    counts, faces = _aggregate_wall_counts(grid, snapshots)
    cells = [[r, c, hits] for (r, c), hits in sorted(counts.items())]
    return {
        "max": max((hits for _, _, hits in cells), default=0),
        "cells": cells,
        "faces": [[r, c, side, hits] for (r, c, side), hits in sorted(faces.items())],
    }


def encode_sequence(grid, snapshots, titles) -> dict:
    """A validated path as ``{frames, turns}``, the pair every player needs.

    Shared by the main solve and by each simplification recipe, so a recipe's
    solution is browsable in the same way as the original instead of being
    reachable only as a folder of images. ``grid`` is needed for the per-turn
    wall-contact highlights.
    """
    return {"frames": _frames(snapshots, titles), "turns": _turns(grid, snapshots, titles)}


def build_run(
    *,
    name,
    grid,
    robot_a,
    robot_b,
    goal_a,
    goal_b,
    snapshots,
    titles,
    switches,
    path,
    solver_seconds=None,
    recipes=None,
) -> dict:
    """Assemble the run record. Pure: it reads state, writes nothing.

    ``solver_seconds`` is elapsed solve time in **seconds**, as a float. The
    record stores the raw number rather than a display string so its unit is
    unambiguous and it stays comparable across runs; the report picks µs / ms /
    s when rendering.
    """
    return {
        "schema": SCHEMA_VERSION,
        "meta": {
            "name": name,
            "rows": grid.rows,
            "cols": grid.cols,
            "n": robot_a.n,
            "switches": switches,
            "solver_seconds": solver_seconds,
            "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        },
        "grid": encode_grid(grid),
        "labels": {"a": robot_a.label, "b": robot_b.label},
        "start": {"a": [robot_a.row, robot_a.col], "b": [robot_b.row, robot_b.col]},
        "goal": {"a": list(goal_a), "b": list(goal_b)},
        # Normalised to one string. The solver returns a list of single-command
        # strings; leaving it a list made the record's own type depend on the
        # caller, and any consumer doing string work on it broke.
        "path": "".join(path) if isinstance(path, (list, tuple)) else (path or ""),
        "frames": _frames(snapshots, titles),
        "turns": _turns(grid, snapshots, titles),
        "heat": _heat(grid, snapshots),
        "recipes": recipes or [],
    }


def write_run(run: dict, out_dir: str) -> str:
    """Write ``run.json``. This is the artifact everything else derives from."""
    os.makedirs(out_dir, exist_ok=True)
    dest = os.path.join(out_dir, RUN_FILENAME)
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(run, fh, separators=(",", ":"))
    return dest


def load_run(run_path: str) -> dict:
    """Read a run.json, refusing one written by an incompatible schema."""
    with open(run_path, encoding="utf-8") as fh:
        run = json.load(fh)
    got = run.get("schema")
    if got != SCHEMA_VERSION:
        raise ValueError(
            f"{run_path}: schema {got!r}, expected {SCHEMA_VERSION}. "
            "Re-run the test to regenerate it."
        )
    return run


# ── HTML ────────────────────────────────────────────────────────────────


def write_local_report(run: dict, out_dir: str, parent_href: str | None = None) -> str:
    """Write the self-contained per-test ``index.html`` beside its run.json.

    ``parent_href`` is the page's "back" link. It defaults to the sibling index
    one level up, which is right for a test folder; a recipe report sits one
    level deeper and passes its own.
    """
    os.makedirs(out_dir, exist_ok=True)
    page = _ENV.get_template("report.html.j2").render(
        title=run["meta"]["name"],
        parent_href=parent_href or f"../{REPORT_FILENAME}",
        report_filename=REPORT_FILENAME,
        palette=palette(),
        # Already JSON, so autoescaping must not touch it -- but a literal
        # "</script>" inside a string value would close the host block early,
        # which is what the "</" substitution prevents.
        run_json=json.dumps(run, separators=(",", ":")).replace("</", "<\\/"),
    )
    dest = os.path.join(out_dir, REPORT_FILENAME)
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(page)
    return dest


def _index_row(run_path: str) -> dict:
    """One table row for the global index, or an error row if unreadable."""
    folder = os.path.basename(os.path.dirname(run_path))
    try:
        run = load_run(run_path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return {"folder": folder, "error": f"{type(exc).__name__}: {exc}"}
    meta, recipes = run["meta"], run.get("recipes", [])
    return {
        "folder": folder,
        "error": None,
        "name": meta["name"],
        "rows": meta["rows"],
        "cols": meta["cols"],
        "n": meta["n"],
        "switches": meta["switches"],
        "steps": len(run["frames"]),
        "recipe_total": len(recipes),
        "recipe_kept": sum(1 for r in recipes if r.get("preserved")),
        "generated": meta["generated"],
    }


def write_global_index(tests_dir: str) -> str | None:
    """Write ``plots/tests/index.html`` over every run.json found beneath it.

    Scans the whole tree rather than only this session's tests, so a filtered
    run still lands on a complete index; each row carries its own generation
    time so a stale entry is visible as stale instead of silently missing.
    Returns None when there is nothing to index.
    """
    runs = sorted(glob.glob(os.path.join(tests_dir, "*", RUN_FILENAME)))
    if not runs:
        return None
    page = _ENV.get_template("index.html.j2").render(
        rows=[_index_row(p) for p in runs],
        report_filename=REPORT_FILENAME,
    )
    dest = os.path.join(tests_dir, REPORT_FILENAME)
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(page)
    return dest
